# IMPORT LIBRARY

In [1]:
import tensorflow as tf
import numpy as np

## tensor shape(5,5) dengan nilai random disimpan dalam variable random_tensor

In [2]:
rb_tensor = tf.random.normal([5,5], mean=0., stddev=1., seed=1)
rb_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

## Tensor shape(5,5) dari list, nilai bilangan prima dalam variable prime_tensor

In [3]:
list_prima = [[19, 53, 5, 7, 13],[11, 17, 2, 23, 59],[31, 37, 47, 43, 97],[3, 29, 61, 1, 73],[79, 83, 89, 41, 71]]

prm_tensor = tf.constant(list_prima, dtype=tf.float32) #create tensor use tf.constant
prm_tensor.numpy()

array([[19., 53.,  5.,  7., 13.],
       [11., 17.,  2., 23., 59.],
       [31., 37., 47., 43., 97.],
       [ 3., 29., 61.,  1., 73.],
       [79., 83., 89., 41., 71.]], dtype=float32)

## Menampilkan dimensi dari kedua variable tersebut

In [4]:
rb_tensor.shape

TensorShape([5, 5])

In [5]:
prm_tensor.shape

TensorShape([5, 5])

## Menampilkan hasil perhitungan aritmetika 2 variable (5 operator)

In [6]:
print("Penjumlahan :",tf.add(prm_tensor,rb_tensor))

Penjumlahan : tf.Tensor(
[[18.188683   54.4846      5.0653296   4.557296   13.099248  ]
 [11.591225   17.592823   -0.12292957 22.277103   58.94373   ]
 [31.643545   36.735676   48.856632   43.56784    96.617165  ]
 [ 1.5146567  30.26177    60.974693    0.7353703  74.532814  ]
 [77.25702    82.5621     88.43399    41.32067    72.13283   ]], shape=(5, 5), dtype=float32)


In [7]:
print("Pengurangan :",tf.subtract(prm_tensor,rb_tensor))

Pengurangan : tf.Tensor(
[[19.811317  51.5154     4.9346704  9.442704  12.900752 ]
 [10.408775  16.407177   4.1229296 23.722897  59.05627  ]
 [30.356455  37.264324  45.143368  42.43216   97.382835 ]
 [ 4.4853435 27.73823   61.025307   1.2646297 71.467186 ]
 [80.74298   83.4379    89.56601   40.67933   69.86717  ]], shape=(5, 5), dtype=float32)


In [8]:
print("Perkalian :",tf.multiply(prm_tensor,rb_tensor))

Perkalian : tf.Tensor(
[[ -15.415046     78.68373       0.32664686  -17.09893       1.2902292 ]
 [   6.5034676    10.077991     -4.245859    -16.626637     -3.3199525 ]
 [  19.949888     -9.77999      87.26176      24.417194    -37.135082  ]
 [  -4.45603      36.591362     -1.5436709    -0.2646297   111.89541   ]
 [-137.69519     -36.345116    -50.37489      13.14744      80.431     ]], shape=(5, 5), dtype=float32)


In [9]:
print("Pembagian :",tf.divide(prm_tensor,rb_tensor))

Pembagian : tf.Tensor(
[[-2.3418678e+01  3.5699883e+01  7.6535255e+01 -2.8656764e+00
   1.3098448e+02]
 [ 1.8605459e+01  2.8676352e+01 -9.4209439e-01 -3.1816418e+01
  -1.0485090e+03]
 [ 4.8170696e+01 -1.3997969e+02  2.5314640e+01  7.5725327e+01
  -2.5337227e+02]
 [-2.0197351e+00  2.2983566e+01 -2.4104880e+03 -3.7788653e+00
   4.7624832e+01]
 [-4.5324749e+01 -1.8954405e+02 -1.5724104e+02  1.2785759e+02
   6.2674839e+01]], shape=(5, 5), dtype=float32)


In [10]:
print("Pangkat :",tf.pow(prm_tensor,rb_tensor))

Pangkat : tf.Tensor(
[[9.1732644e-02 3.6295920e+02 1.1108701e+00 8.6233392e-03 1.2899032e+00]
 [4.1275911e+00 5.3633776e+00 2.2958025e-01 1.0365988e-01 7.9497504e-01]
 [9.1150293e+00 3.8502288e-01 1.2719568e+03 8.4635296e+00 1.7353715e-01]
 [1.9557400e-01 7.0018288e+01 9.0119815e-01 1.0000000e+00 7.1800415e+02]
 [4.9258291e-04 1.4442728e-01 7.8818068e-02 3.2898054e+00 1.2507278e+02]], shape=(5, 5), dtype=float32)


## Nilai maksimal dan minimal dari variable random_tensor 

In [11]:
tf.argmax(rb_tensor, axis=1). numpy() #nilai max dari kolom(axis=1)

array([1, 1, 2, 4, 4], dtype=int64)

In [12]:
tf.argmin(rb_tensor, axis=1). numpy() #nilai min dari kolom(axis=1)

array([3, 2, 4, 0, 0], dtype=int64)

In [13]:
tf.argmax(rb_tensor, axis=0). numpy() #nilai max dari baris(axis=0)

array([2, 0, 2, 2, 3], dtype=int64)

In [14]:
tf.argmin(rb_tensor, axis=0). numpy() #nilai min dari baris(axis=0)

array([4, 4, 1, 0, 2], dtype=int64)

## Penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [15]:
tf.concat([rb_tensor, prm_tensor], axis=1) #penggabungan kolom

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02,  1.9000000e+01,  5.3000000e+01,  5.0000000e+00,
         7.0000000e+00,  1.3000000e+01],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02,  1.1000000e+01,  1.7000000e+01,  2.0000000e+00,
         2.3000000e+01,  5.9000000e+01],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01,  3.1000000e+01,  3.7000000e+01,  4.7000000e+01,
         4.3000000e+01,  9.7000000e+01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00,  3.0000000e+00,  2.9000000e+01,  6.1000000e+01,
         1.0000000e+00,  7.3000000e+01],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         4.1000000e+01,  7.1000000e+01]], dtype=float32)>

In [16]:
tf.concat([rb_tensor, prm_tensor], axis=0) #penggabungan baris

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-8.1131822e-01,  1.4845988e+00,  6.5329373e-02, -2.4427042e+00,
         9.9248402e-02],
       [ 5.9122431e-01,  5.9282297e-01, -2.1229296e+00, -7.2289723e-01,
        -5.6270380e-02],
       [ 6.4354479e-01, -2.6432407e-01,  1.8566332e+00,  5.6784171e-01,
        -3.8283589e-01],
       [-1.4853433e+00,  1.2617711e+00, -2.5306080e-02, -2.6462969e-01,
         1.5328138e+00],
       [-1.7429771e+00, -4.3789294e-01, -5.6601000e-01,  3.2066926e-01,
         1.1328310e+00],
       [ 1.9000000e+01,  5.3000000e+01,  5.0000000e+00,  7.0000000e+00,
         1.3000000e+01],
       [ 1.1000000e+01,  1.7000000e+01,  2.0000000e+00,  2.3000000e+01,
         5.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.7000000e+01,  4.3000000e+01,
         9.7000000e+01],
       [ 3.0000000e+00,  2.9000000e+01,  6.1000000e+01,  1.0000000e+00,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  4.1000000e+01,
      

## Hasil sorting kedua variable di atas. (descending)

In [17]:
sort_rb_tensor1 = tf.sort(rb_tensor, direction="DESCENDING") 
sort_rb_tensor1.numpy()

array([[ 1.4845988 ,  0.0992484 ,  0.06532937, -0.8113182 , -2.4427042 ],
       [ 0.59282297,  0.5912243 , -0.05627038, -0.72289723, -2.1229296 ],
       [ 1.8566332 ,  0.6435448 ,  0.5678417 , -0.26432407, -0.3828359 ],
       [ 1.5328138 ,  1.2617711 , -0.02530608, -0.2646297 , -1.4853433 ],
       [ 1.132831  ,  0.32066926, -0.43789294, -0.56601   , -1.7429771 ]],
      dtype=float32)

In [18]:
sort_prm_tensor1 = tf.sort(prm_tensor, direction="DESCENDING")
sort_prm_tensor1.numpy()

array([[53., 19., 13.,  7.,  5.],
       [59., 23., 17., 11.,  2.],
       [97., 47., 43., 37., 31.],
       [73., 61., 29.,  3.,  1.],
       [89., 83., 79., 71., 41.]], dtype=float32)

In [19]:
sort_rb_tensor2 = tf.argsort(rb_tensor, direction="DESCENDING") 
sort_rb_tensor2.numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [20]:
sort_prm_tensor2 = tf.argsort(prm_tensor, direction="DESCENDING")
sort_prm_tensor2.numpy()

array([[1, 0, 4, 3, 2],
       [4, 3, 1, 0, 2],
       [4, 2, 3, 1, 0],
       [4, 2, 1, 0, 3],
       [2, 1, 0, 4, 3]])